Repository canonical/juju.is, pull requests merged in 2020-07, with the labels that each got.

#80 Redirect cloud-init.io to juju.is
  deploy/site.yaml
Labels: Review: Code +1, Review: QA +1

#84 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#82 Redirect conjure-up.io instead of cloud-init.io
  konf/site.yaml
Labels: Review: Code +1, Review: QA +1

#85 Redirect staging aliases to staging.juju.is
  konf/site.yaml
Labels: Review: Code +1
