Repository canonical/juju.is, pull requests merged in 2020-10, with the labels that each got.

#149 Update illustrations on the homepage
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#145 Fix get-in-touch buttons spacing on mobile
  static/sass/_patterns_p-modal.scss
  templates/partials/_get-in-touch.html
Labels: Review: Code +1, Review: QA +1, hacktoberfest-accepted

#151 Update GTM and add cookie policy
  package.json
  static/sass/styles.scss
  templates/base.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#154 Add Operator Framework CTA to footer
  static/sass/styles.scss
  templates/base.html
  templates/footer.html
Labels: Review: Code +1, Review: QA +1

#155 Add hero logo padding on small screens
  static/js/tabpanel.js
  static/sass/_patterns_hero-tab.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#156 Fix search page layout bugs
  static/sass/styles.scss
  templates/docs/search.html
Labels: Review: Code +1, Review: QA +1
