Repository canonical/juju.is, pull requests merged in 2020-09, with the labels that each got.

#110 Add the About overview page
  templates/about/base.html
  templates/about/index.html
  templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#111 Add the multi-cloud-ops about page
  templates/about/base.html
  templates/about/index.html
  templates/about/multi-cloud-operations.html
Labels: Review: Code +1, Review: QA +1

#115 Build the about hosted-olm page
  templates/about/base.html
  templates/about/hosted-olm.html
Labels: Review: Code +1, Review: QA +1

#118 Build the about ops-code-quality page
  templates/about/base.html
  templates/about/ops-code-quality.html
Labels: Review: Code +1, Review: QA +1

#120 About operator lifecycle manager
  templates/about/base.html
  templates/about/operator-lifecycle-manager.html
Labels: Review: Code +1, Review: QA +1

#121 About architecture
  templates/about/architecture.html
  templates/about/base.html
Labels: Review: Code +1, Review: QA +1

#122 Build the about high-availability-enterprise-olm page
  templates/about/base.html
  templates/about/high-availability-enterprise-olm.html
Labels: Review: Code +1, Review: QA +1

#113 Build the about mission page
  templates/about/base.html
  templates/about/mission.html
Labels: Review: Code +1, Review: QA +1

#119 Build the about operator-services page
  templates/about/base.html
  templates/about/operator-services.html
Labels: Review: Code +1, Review: QA +1

#117 Build the about universal-operators page
  templates/about/base.html
  templates/about/universal-operators.html
Labels: Review: Code +1, Review: QA +1

#116 Build the about devsecops page
  templates/about/base.html
  templates/about/devsecops.html
Labels: Review: Code +1, Review: QA +1

#114 Build the about model-driven-operations page
  templates/about/base.html
  templates/about/model-driven-operations.html
Labels: Review: Code +1, Review: QA +1

#112 Build the about integration page
  templates/about/base.html
  templates/about/integration.html
Labels: Review: Code +1, Review: QA +1

#126 Update about content
  requirements.txt
  run
  templates/about/architecture.html
  templates/about/base.html
  templates/about/beyond-configuration-management.html
  templates/about/hosted-olm.html
  templates/about/integration.html
  templates/about/mission.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/universal-operators.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#125 Build the homepage
  static/sass/styles.scss
  templates/base.html
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#128 Change some titles in the about pages
  templates/about/high-availability-enterprise-olm.html
  templates/about/model-driven-operations.html
  templates/about/ops-code-quality.html
Labels: Review: Code +1, Review: QA +1

#127 Add a contact us form
  templates/base.html
  templates/contact-us.html
  templates/thank-you.html
Labels: Review: Code +1, Review: QA +1

#129 Address feedback
  package.json
  static/sass/_patterns_navigation.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/about/base.html
  templates/about/model-driven-operations.html
  templates/base.html
  templates/contact-us.html
  templates/index.html
  templates/tutorials/index.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#130 Add ids
  templates/about/architecture.html
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/high-availability-enterprise-olm.html
  templates/about/hosted-olm.html
  templates/about/index.html
  templates/about/integration.html
  templates/about/mission.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/ops-code-quality.html
  templates/about/universal-operators.html
Labels: Review: Code +1 (with changes), Review: QA +1

#131 Fix sticky header
  static/sass/styles.scss
  templates/tutorials/tutorial.html
Labels: Review: Code +1, Review: QA +1

#124 Demo!!
  package.json
  requirements.txt
  run
  static/sass/_patterns_navigation.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/about/architecture.html
  templates/about/base.html
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/high-availability-enterprise-olm.html
  templates/about/hosted-olm.html
  templates/about/index.html
  templates/about/integration.html
  templates/about/mission.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/ops-code-quality.html
  templates/about/universal-operators.html
  templates/base.html
  templates/contact-us.html
  templates/index.html
  templates/thank-you.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  webapp/app.py
  yarn.lock
Labels: Review: QA +1

#134 Add penguin logo to homepage
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#133 Rename /about to /overview and make /mission the index
  templates/base.html
  templates/overview/architecture.html
  templates/overview/base.html
  templates/overview/beyond-configuration-management.html
  templates/overview/devsecops.html
  templates/overview/high-availability-enterprise-olm.html
  templates/overview/hosted-olm.html
  templates/overview/index.html
  templates/overview/integration.html
  templates/overview/mission.html
  templates/overview/model-driven-operations.html
  templates/overview/multi-cloud-operations.html
  templates/overview/operator-lifecycle-manager.html
  templates/overview/operator-services.html
  templates/overview/ops-code-quality.html
  templates/overview/universal-operators.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#135 Add new suru on homepage
  static/sass/_patterns_navigation.scss
  static/sass/_patterns_strips.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#136 Fix about pages
  templates/about/architecture.html
  templates/about/base.html
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/high-availability-enterprise-olm.html
  templates/about/hosted-olm.html
  templates/about/index.html
  templates/about/integration.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/olm-overview.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/ops-code-quality.html
  templates/about/universal-operators.html
  templates/base.html
  webapp/app.py
Labels: Review: Code +1, Review: QA -1

#138 Update about navigation
  templates/about/base.html
  templates/about/mission.html
  templates/about/overview.html
  templates/base.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#139 Add redirect
  redirects.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#141 Linkify site
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/hosted-olm.html
  templates/about/integration.html
  templates/about/model-driven-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#143 Add dynamic get-in-touch-form
  .github/pull_request_template.md
  static/js/dynamic-contact-form.js
  static/sass/_patterns_p-modal.scss
  static/sass/styles.scss
  templates/base.html
  templates/partials/_get-in-touch.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
