Repository canonical/juju.is, pull requests merged in 2020-03, with the labels that each got.

#26 Latest homepage copy changes
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#27 Update error pages and fix indentation
  templates/404.html
  templates/500.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#24 Multistage builds for juju.is
  .dockerignore
  .env
  Dockerfile
  package.json
Labels: Review: Code +1, Review: QA +1

#28 Double the slideshow duration
  static/js/tabpanel.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#31 Fix grammar of "Juju is alternative to OpenShift"
  templates/index.html
Labels: Review: Code +1

#32 Fix links on docs homepage
  templates/docs/homepage.html
Labels: Review: Code +1, Review: QA +1

#33 Search juju.is/docs instead of docs.jujucharms.com
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#34 Enable and recommend dotrun snap
  .gitignore
  README.md
  package.json
  requirements.txt
  yarn.lock
Labels: Review: Code +1, Review: QA needed

#36 Pad pagination buttons
  templates/docs/search.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#41 Update discourseAPI to juju.is.
  webapp/docs/views.py
Labels: Review: Code +1

#43 Apply the navigation functionality to the small screen docs
  templates/docs/base.html
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1
