Repository canonical/juju.is, pull requests merged in 2020-11, with the labels that each got.

#158 Build the community page
  templates/community.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#160 Update community link
  requirements.txt
  static/sass/styles.scss
  templates/base.html
  templates/docs/search.html
  templates/footer.html
  templates/index.html
  templates/thank-you.html
  webapp/docs/views.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#161 Fix docs title
  templates/docs/base.html
Labels: Review: Code +1

#162 Update variable page_title
  templates/about/architecture.html
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/high-availability-enterprise-olm.html
  templates/about/hosted-olm.html
  templates/about/integration.html
  templates/about/mission.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/ops-code-quality.html
  templates/about/overview.html
  templates/about/universal-operators.html
Labels: Review: Code +1 (with changes), Review: QA +1

#163 Revert the community page content to the original content
  templates/community.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
