Repository canonical/juju.is, pull requests merged in 2021-06, with the labels that each got.

#253 Add syntax highlighting to docs
  static/js/highlight.pack.js
  static/js/prism.js
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1

#255 Fix header height
  package.json
  static/sass/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1

#257 Fix docs headers being hidden by sticky header
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#259 Update discourse docs
  requirements.txt
Labels: Review: Code +1 (with changes), Review: QA +1

#265 Update manifesto title
  templates/model-driven-operations-manifesto.html
Labels: Review: Code +1, Review: QA +1

#267 Update styles.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#271 Add k8s survey holding page
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#270 K8s survey page
  static/sass/_patterns_p-survey-chart.scss
  static/sass/styles.scss
  templates/cloud-native-kubernetes-usage-report-2021/index.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#272 Update copy on k8s survey page
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#276 Add scroll padding to k8s report
  static/sass/styles.scss
Labels: QA -1, Review: Code +1

#278 Update quotations on k8s report page
  static/sass/_patterns_p-survey-chart.scss
  static/sass/styles.scss
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#279 Close side nav on mobile when clicking link
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#277 Changes on k8s report page
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#284 Make survey charts legible on mobile
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#290 Update copy on k8s report
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#289 Update k8s report survey answer
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#288 Update k8s report page title
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#291 Fix report navigation link
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#293 Update k8s report meta description
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1

#296 Add meta image to k8s survey report page
  templates/base.html
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1
