Repository canonical/juju.is, pull requests merged in 2021-04, with the labels that each got.

#181 Add hiring link to global nav
  templates/base.html
Labels: Review: Code +1

#183 Use greenhouse field "Canonical site" instead of department
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1

#184 Add tutorials filtering by topics
  static/js/tutorials-list.js
  templates/tutorials/index.html
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#185 Fix tutorials categories
  templates/tutorials/index.html
Labels: Review: Code +1, Review: QA +1

#186 Add sdk docs to juju.is
  webapp/app.py
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#187 Bump flask base 0.9
  requirements.txt
Labels: Review: Code +1

#191 Update formating of GTM tags to allow verification
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#195 Manage multiple tutorial topics
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#188 Build the new navigation
  static/js/navigation.js
  static/sass/_patterns_cards.scss
  static/sass/_patterns_navigation.scss
  static/sass/_patterns_p-subnav.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/base.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#200 Fix learn to be highlighted when on /docs/sdk
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#198 About page
  redirects.yaml
  static/js/tabs.js
  static/sass/_patterns_cards.scss
  static/sass/_patterns_strips.scss
  static/sass/_patterns_tabs.scss
  static/sass/styles.scss
  templates/about/_practices_tabs.html
  templates/about/_technology_tabs.html
  templates/about/architecture.html
  templates/about/base.html
  templates/about/beyond-configuration-management.html
  templates/about/devsecops.html
  templates/about/high-availability-enterprise-olm.html
  templates/about/hosted-olm.html
  templates/about/index.html
  templates/about/integration.html
  templates/about/mission.html
  templates/about/model-driven-operations.html
  templates/about/multi-cloud-operations.html
  templates/about/operator-lifecycle-manager.html
  templates/about/operator-services.html
  templates/about/ops-code-quality.html
  templates/about/overview.html
  templates/about/universal-operators.html
  templates/footer.html
  templates/partials/_navigation.html
  webapp/app.py
Labels: Review: Design +1

#201 Update docs and tutorials
  konf/site.yaml
  requirements.txt
  templates/tutorials/index.html
  webapp/docs/views.py
  webapp/tutorials/views.py
Labels: Review: Code needed, Review: QA needed

#199 New footer
  static/sass/_patterns_icons.scss
  static/sass/styles.scss
  templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#203 Add missing social links to footer
  static/sass/_patterns_icons.scss
  templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#204 Add create an Operator with the SDK link
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#205 Update community page
  templates/community.html
Labels: Review: Code +1, Review: QA +1

#208 Add support for links on level 0 docs nav items
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1

#209 Fix navigation js not to use ES6
  templates/base.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA needed

#206 New homepage
  package.json
  static/js/carousels.js
  static/sass/_patterns_carousel.scss
  static/sass/styles.scss
  templates/index.html
  templates/partials/_contributors.html
  templates/partials/_juju-supports.html
  templates/partials/_take-control.html
  templates/partials/_testimonials.html
  yarn.lock
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#210 Add juju supports logos
  templates/partials/_juju-supports.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#212 Add model driven operations manifesto
  templates/footer.html
  templates/model-driven-operations-manifesto.html
Labels: Review: Code +1, Review: QA +1

#192 Add olm docs
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#218 Add featured articles
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1

#214 New homepage what is juju
  static/js/what-is-juju.js
  static/sass/_patterns_heading-highlight.scss
  static/sass/_patterns_scroller.scss
  static/sass/_patterns_what-is-juju.scss
  static/sass/styles.scss
  templates/index.html
  templates/partials/_what-is-juju.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#220 Update the install link on the homepage
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#219 New homepage
  package.json
  static/js/carousels.js
  static/js/what-is-juju.js
  static/sass/_patterns_carousel.scss
  static/sass/_patterns_heading-highlight.scss
  static/sass/_patterns_scroller.scss
  static/sass/_patterns_what-is-juju.scss
  static/sass/styles.scss
  templates/index.html
  templates/partials/_contributors.html
  templates/partials/_juju-supports.html
  templates/partials/_take-control.html
  templates/partials/_testimonials.html
  templates/partials/_what-is-juju.html
  yarn.lock
Labels: Review: Code +1

#221 Update footer links
  templates/footer.html
  templates/partials/_what-is-juju.html
Labels: Review: Code +1, Review: QA +1

#202 Add marketo form to /about
  templates/about/_ebook-signup-form.html
  templates/about/index.html
Labels: Review: Code +1, Review: QA +1

#225 Update links in footer
  templates/footer.html
Labels: Review: Code +1, Review: QA +1
