Repository canonical/juju.is, pull requests merged in 2021-05, with the labels that each got.

#223 Update the blog section
  static/sass/_patterns_cards.scss
  static/sass/_settings.scss
  static/sass/_utility_crop.scss
  static/sass/styles.scss
  templates/blog/_blog-card.html
  templates/blog/_newsletter-signup.html
  templates/blog/article.html
  templates/blog/index.html
  templates/blog/partials/_blog-card.html
  templates/blog/partials/_blog-card_aside.html
  templates/blog/partials/_blog-card_featured.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#229 Enable the cookie policy
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#211 Implement filters on tutorials page
  package.json
  static/js/tutorials-list.js
  static/sass/_patterns_cards.scss
  static/sass/_patterns_l-fluid-breakout.scss
  static/sass/_patterns_navigation.scss
  static/sass/_patterns_tutorials.scss
  static/sass/styles.scss
  templates/tutorials/index.html
  webapp/tutorials/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#232 Make the what is juju animation responsive to the font size
  static/sass/_patterns_what-is-juju.scss
Labels: Review: Code +1, Review: QA +1

#240 Change dependencies order to avoid Flask 2.0
  requirements.txt
Labels: Review: Code needed

#238 Add hero typer to homepage
  static/js/typer.js
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#242 Enable the typer on small screens
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#227 Update site logo to link to home page
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#244 Add versioned static to static assets
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#245 Fix tutorial page
  static/sass/_patterns_tutorials.scss
  static/sass/styles.scss
  templates/tutorials/tutorial.html
Labels: Review: Code +1 (with changes), Review: QA +1

#248 Update vanilla and fix tutorial layout
  package.json
  static/sass/_patterns_docs.scss
  static/sass/_patterns_navigation.scss
  static/sass/_patterns_tutorials.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#249 Switch from node sass to sass
  .stylelintrc
  package.json
  static/sass/_hljs.scss
  static/sass/_patterns_cards.scss
  static/sass/_patterns_carousel.scss
  static/sass/_patterns_docs.scss
  static/sass/_patterns_heading-highlight.scss
  static/sass/_patterns_icons.scss
  static/sass/_patterns_scroller.scss
  static/sass/_patterns_strips.scss
  static/sass/_patterns_what-is-juju.scss
  static/sass/_settings.scss
  static/sass/_utility_crop.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#251 Fix pagination arrows on tutorials
  static/sass/_patterns_tutorials.scss
Labels: Review: Code +1, Review: QA +1
