Repository canonical/juju.is, pull requests merged in 2022-05, with the labels that each got.

#399 Updates for about page
  templates/about/_practices_tabs.html
  templates/about/index.html
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#397 Update index page (due 12/05/22)
  static/js/dynamic-contact-form.js
  static/sass/_patterns_heading-highlight.scss
  templates/careers.html
  templates/contact-us.html
  templates/docs/search.html
  templates/index.html
  templates/partials/_get-in-touch.html
  templates/partials/_navigation.html
  templates/partials/_take-control.html
  templates/partials/_testimonials.html
  templates/partials/_what-is-juju.html
  templates/thank-you.html
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#395 Build 2022 report
  templates/cloud-native-kubernetes-usage-report-2022/index.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#400 Remove the duplicated stat on the k8s report 2022
  templates/cloud-native-kubernetes-usage-report-2022/index.html
Labels: Review: Code +1 (with changes)

#401 Small fixes for operator day
  templates/about/index.html
  templates/partials/_navigation.html
Labels: Review: Code +1

#402 About page hero strip shallow
  templates/about/index.html
Labels: Review: Design needed, Review: Code +1

#405 Remove the heading classes to make room on lower resolutions
  templates/partials/_what-is-juju.html
Labels: Review: Code +1, Review: QA +1
