Repository canonical/juju.is, pull requests merged in 2023-03, with the labels that each got.

#450 Operator day
  static/images/operator-day/0 - David Booth.jpg
  static/images/operator-day/0 - Mark Shuttleworth.jpg
  static/images/operator-day/1-jon-seager.jpg
  static/images/operator-day/2-pietro-pasotti.jpg
  static/images/operator-day/3-alexjones.jpg
  static/images/operator-day/4-jamesbeedy.jpg
  static/images/operator-day/4-jonthor.jpg
  static/images/operator-day/5 - Billy Olsen.jpg
  static/images/operator-day/5-jamespage.jpg
  static/images/operator-day/5b - Anton Smith.jpg
  static/images/operator-day/6-moritz.jpg
  static/images/operator-day/7-alessio.jpg
  static/images/operator-day/8-rajan-headshot-cropped.jpg
  static/images/operator-day/9-seijas.jpg
  static/images/operator-day/9-tom2.jpg
  static/images/operator-day/9-varshi.jpg
  static/images/operator-day/image1.jpg
  static/images/operator-day/image10.jpg
  static/images/operator-day/image11.jpg
  static/images/operator-day/image12.jpg
  static/images/operator-day/image13.jpg
  static/images/operator-day/image15.jpg
  static/images/operator-day/image16.jpg
  static/images/operator-day/image17.jpg
  static/images/operator-day/image18.jpg
  static/images/operator-day/image19.jpg
  static/images/operator-day/image2.jpg
  static/images/operator-day/image20.jpg
  static/images/operator-day/image21.jpg
  static/images/operator-day/image22.jpg
  static/images/operator-day/image23.jpg
  static/images/operator-day/image24.jpg
  static/images/operator-day/image25.jpg
  static/images/operator-day/image26.jpg
  static/images/operator-day/image28.jpg
  static/images/operator-day/image29.jpg
  static/images/operator-day/image3.jpg
  static/images/operator-day/image30.jpg
  static/images/operator-day/image32.jpg
  static/images/operator-day/image33.jpg
  static/images/operator-day/image34.jpg
  static/images/operator-day/image36.jpg
  static/images/operator-day/image37.jpg
  static/images/operator-day/image39.jpg
  static/images/operator-day/image4.jpg
  static/images/operator-day/image5.jpg
  static/images/operator-day/image6.jpg
  static/images/operator-day/image7.jpg
  static/images/operator-day/image8.jpg
  static/images/operator-day/image9.jpg
  templates/operator-day/index.html
  templates/operator-day/kubecon-eu-2021.html
  templates/operator-day/kubecon-eu-2022.html
  templates/operator-day/kubecon-na-2020.html
  templates/operator-day/kubecon-na-2021.html
  templates/operator-day/kubecon-na-2022.html
Labels: Review: Design +1, Review: Code +1, Review: QA +1, Review: UX +1, Review: PdM +1

#453 Remove JAAS from navigation
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1

#455 Provide "/latest.json" endpoint for Dashboard checks
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#456 Add caching for juju and jaas versioning
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#459 allow all CORS
  requirements.txt
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#460 Feature strip title stick to the top
  static/sass/_patterns_what-is-juju.scss
Labels: Review: Code +1, Review: QA +1

#462 Update redirects.yaml for tutorial redirects
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#463 Remove Tutorials code
  static/js/tutorials-list.js
  static/sass/_patterns_cards.scss
  static/sass/_patterns_tutorials.scss
  static/sass/styles.scss
  templates/partials/_navigation.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  webapp/app.py
  webapp/docs/views.py
  webapp/tutorials/__init__.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1
