Repository canonical/juju.is, pull requests merged in 2023-11, with the labels that each got.

#501 Upgrade canonicalwebteam.discourse to 5.4.5
  requirements.txt
Labels: Review: QA +1, Review: Code +1 (with changes)

#502 Fix srcset with latest discourse module
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#504 Add Github buttons
  static/sass/styles.scss
  templates/index.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#503 Remove links to about page and ebook section
  templates/about/index.html
  templates/cloud-native-kubernetes-usage-report-2021/index.html
Labels: Review: Code +1, Review: QA +1
