Repository canonical/juju.is, pull requests merged in 2023-01, with the labels that each got.

#438 Update navigation link
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#439 Update blog filtering wd 762
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#441 Fix the ebook form
  templates/about/_ebook-signup-form.html
Labels: Review: Code needed, Review: QA needed

#443 Update title used on opengraph
  templates/base.html
Labels: Review: Code +1, Review: QA +1
