Repository canonical/juju.is, pull requests merged in 2023-02, with the labels that each got.

#445 Add Interfaces to navigation. Update nagivation to match CH
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#446 Add page meta title
  templates/about/index.html
  templates/base.html
  templates/careers.html
  templates/cloud-native-kubernetes-usage-report-2021/index.html
  templates/cloud-native-kubernetes-usage-report-2022/index.html
  templates/community.html
  templates/contact-us.html
  templates/docs/base.html
  templates/docs/search.html
  templates/model-driven-operations-manifesto.html
  templates/thank-you.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
Labels: Review: Code needed, Review: QA needed

#447 Fix title block bug
  templates/about/index.html
  templates/model-driven-operations-manifesto.html
Labels: Review: Code +1, Review: QA +1

#448 Disable interfaces link
  templates/partials/_navigation.html
Labels: Review: Code +1

#449 Update to meta tags
  templates/about/index.html
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#451 Fix global nav
  package.json
  static/sass/_patterns_navigation.scss
  templates/base.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1
