Repository canonical/juju.is, pull requests merged in 2024-07, with the labels that each got.

#540 chore: Bump canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0
  package.json
  requirements.txt
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#541 chore: Adds redirect for /docs/olm/install-juju
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#542 chore: Adds redirect to /docs/juju/install-and-manage-the-client
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#543 chore: Bumps canonicalwebteam.discourse version
  requirements.txt
Labels: Review: Code +1

#544 chore: Downgrades `@canonical/cookie-policy` to 3.5.0
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#545 Update copyright in footer
  templates/footer.html
Labels: Review: QA +1
