Repository canonical/juju.is, pull requests merged in 2024-01, with the labels that each got.

#508 feat(copy): Update operator-day pages
  templates/operator-day/index.html
  templates/operator-day/kubecon-eu-2023.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM needed

#511 fix: update dotrun install in pr workflow
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1

#487 Remove text-width limit for docs
  static/sass/_patterns_docs.scss
Labels: Review: Design needed, Review: UX needed, Review: Code +1, Review: QA +1

#510 Upgrade to vanilla-4.5.0 & implement new documentation layout
  static/sass/_patterns_docs.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/base.html
  templates/careers.html
  templates/docs/base.html
  templates/docs/document.html
  templates/docs/search.html
  templates/footer.html
  templates/partials/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: PdM +1
