Repository canonical/juju.is, pull requests merged in 2025-02, with the labels that each got.

#565 Juju ecosystem docs refresh
  redirects.yaml
  requirements.txt
  static/sass/styles.scss
  templates/base.html
  templates/docs/base.html
  templates/docs/document.html
  templates/docs/juju-ecosystem-docs.html
  templates/docs/search.html
  templates/partials/_juju-ecosystem-docs-footer.html
  templates/partials/_navigation.html
  webapp/app.py
  webapp/docs/search.py
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#568 update RTD redirects to include `/?`
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#569 Juju ecosystem docs post-release fixes
  static/sass/styles.scss
  templates/docs/juju-ecosystem-docs.html
Labels: Review: Code +1, Review: QA +1

#570 fix typo on docs page
  templates/docs/juju-ecosystem-docs.html
Labels: Review: Code +1, Review: QA +1

#571 add missing clouds
  templates/docs/juju-ecosystem-docs.html
Labels: Review: Code +1, Review: QA +1

#572 Copy update: change trusted by on homepage WD-19628
  templates/index.html
Labels: Review: Code +1
